---

name: Test

on:
  push:
    branches: [latest]
    paths:
      - '**.py'
      - '**.go'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'
  pull_request:
    branches: [latest]
    paths:
      - '**.py'
      - '**.go'
      - '.github/workflows/test.yml'
      - 'requirements_test.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt >/dev/null
          pip install -r examples/requirements.txt >/dev/null

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'src/go.mod'

      - name: Building Go Binaries
        run: |
          bash src/cmd/build.sh
          bash src/lib/build.sh

      - name: Running Unit Tests
        run: |
          python3 -m pytest --version
          python3 -m pytest

      - name: Running examples
        run: |
          python3 examples/minimal_cgo.py
          python3 examples/generate_map_cli.py
          python3 examples/generate_map_cgo.py
